# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Thomas Alvarenga
subtitle: "Um blog de um programador apaixonado por boas práticas e metodologias ágeis"
email: alvarenga.thomas@gmail.com
name: Thomas Alvarenga
description: >
  Um blog sobre boas práticas de desenvolvimento de software e metodologias ágeis
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://alvarengathomas.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.svg"

# Build settings
markdown: kramdown
permalink: /:title
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai_sublime"

# Google analytics
ga_tracking_id: "UA-84953583-1"

social:
  - name: Twitter
    icon: twitter
    username: thomasalvarenga
    url: https://twitter.com/thomasalvarenga
    desc: Me siga no Twitter
    share: true

  - name: GitHub
    icon: github
    username: alvarengathomas
    url: https://github.com/alvarengathomas
    desc: Me siga no GitHub
    share: false

  - name: Facebook
    icon: facebook
    username: blogthomasalvarenga
    url: https://www.facebook.com/blogthomasalvarenga/
    desc: Curta minha página no facebook
    share: true

protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/alvarengathomas/alvarengathomas.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:alvarengathomas/alvarengathomas.github.io.git"
