# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Thomas Alvarenga
subtitle: "Um blog de um programador apaixonado por boas práticas e metodologias ágeis"
email: alvarenga.thomas@gmail.com
name: Thomas Alvarenga
description: >
  Nós acreditamos que o desenvolvimento de software não precisa ser difícil e estressante, o que causa isso é a falta de conhecimento dos programadores a respeito das técnicas e boas práticas necessárias para se construir um sistema de qualidade em pouco tempo e que realmente facilite a vida de seus clientes e automatize processos em empresas.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alvarengathomas.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
permalink: /:title
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai_sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: thomsalvarenga

# Google analytics
ga_tracking_id: "UA-84953583-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: thomasalvarenga
    url: https://twitter.com/thomasalvarenga
    desc: Me siga no Twitter
    share: true

  - name: GitHub
    icon: github
    username: alvarengathomas
    url: https://github.com/alvarengathomas
    desc: Fork me on GitHub
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/alvarengathomas/alvarengathomas.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:alvarengathomas/alvarengathomas.github.io.git"
